### ISSUE TITLE
GitHub API v2: End of Life 

### ISSUE THREAD

**Issue by dave-hansen** [ornicar/php-github-api#31] opened 2012-06-13 18:11 UTC
GitHub has sunsetted the v2 library, see their blog post [here](https://github.com/blog/1160-github-api-v2-end-of-life):

Authentication works, but anything after that fires Curl exception for a 404:

```
PHP Fatal error:  Uncaught exception 'Github_HttpClient_Exception' with message 'HTTP 404: Not Found' in lib/Github/HttpClient/Curl.php:73
Stack trace:
#0 lib/vendor/Github/HttpClient.php(105): Github_HttpClient_Curl->doRequest('http://github.c...', Array, 'GET', Array)
#1 lib/vendor/Github/HttpClient.php(62): Github_HttpClient->request('pulls/BRANCH...', Array, 'GET', Array)
#2 lib/vendor/Github/Client.php(104): Github_HttpClient->get('pulls/BRANCH...', Array, Array)
#3 lib/vendor/Github/Api.php(33): Github_Client->get('pulls/BRANCH...', Array, Array)
#4 lib/vendor/Github/Api/PullRequest.php(24): Github_Api->get('pulls/BRANCH...')
#5 lib/PullRequests.class.php(35): Github_Api_PullRequest->listPullRequests('BRANCH', 'REPO', 'open')
#6 SCRIPT in lib/vendor/Github/HttpClient/Curl.php on line 73
```

**Comment by ornicar** [comment] 2012-06-13 20:16
Well I guess that means the end of life of this library.

**Comment by katanacrimson** [comment] 2012-06-13 20:16
Duplicate of #22, #25.

**Comment by ornicar** [comment] 2012-06-13 20:34
https://github.com/ornicar/php-github-api/commit/c4705f0b3c56da64059bf8b59d89540a2a698382

**Closed as completed by ornicar** 2012-06-13 20:34 UTC
