### ISSUE TITLE
v3 support

### ISSUE THREAD

**Issue by jwhitcraft** [ornicar/php-github-api#25] opened 2012-02-07 00:20 UTC
Just wondering when/if this will every support the v3 api?

**Comment by dmyers** [comment] 2012-04-13 02:09
Me too!

**Comment by jameswilson** [comment] 2012-05-03 02:18
Duplicate of #22 (OAuth support).

**Comment by Enissay** [comment] 2012-05-03 23:20
I just started using this 2 months ago... I've really no luck :( 
I hope v3 will be supported soon ...

**Comment by mdale** [comment] 2012-05-11 00:48
+1

**Comment by sebilasse** [comment] 2012-05-23 10:27
+2

**Comment by ornicar** [comment] 2012-06-13 20:34
https://github.com/ornicar/php-github-api/commit/c4705f0b3c56da64059bf8b59d89540a2a698382

**Closed as completed by ornicar** 2012-06-13 20:34 UTC
